name: qr_code_scanner_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #material
  cupertino_icons: ^1.0.2
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  #qr
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  #cache
  shared_preferences: ^2.2.2
  #state
  flutter_riverpod: ^2.4.3
  #permission
  permission_handler: ^11.0.1
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf
